alkemyTech/OT155-JS-server

app.js, bin/www, controllers/organizations.controller.js, routes/organizations.js
The route to the organizations endpoint was added and the GET request was made to the database searching for the organization id.
A json response is returned with the data requested in the ticket.
Note:
The database model was not created, it was not requested in the ticket.
=> OT155-17 -Endpoint - public data Organization

README.md, seeders/20201109013159-create-demo-user.js
###Sumary 
- Seeder created 
- 10 Admin users 
- 10 Standart users
=> Ot155 94 Crear seed de Usuarios

seeders/20201109013160-create-Activities.js
=> OT155-69 Crear seeders para guardar Actividades existentes de la ONG

app.js, auth/authRole.js, controllers/news.controllers.js, models/new.js, routes/news.js
* created controller getNews
* created model News
* created routet News
[OT155-45 LINK](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT155/boards/229?modal=detail&selectedIssue=OT155-45)
=> OT155-45 Endpoint Listado de Novedades

auth/authRole.js
* created Middleware auth role
[OT155-52 LINK](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT155/boards/229?modal=detail&selectedIssue=OT155-52)
=> OT155-52 Middleware para verificar usuario administrador

bin/www, migrations/20220321124203-create-testimonials.js, models/testimonials.js
Create testimonials table
Create Migration and model
=> OT155-14 - Create Model and migration of testimonial table

bin/www, controllers/user.controller.js, models/index.js, models/user.js, package-lock.json, package.json, routes/users.js
- Create User Model
- Create Login endpoint
- Create Login controller
_Postman screenshots_
- Successful request:
- Invalid password:
- Invalid Email
=> Ot155 25 - Login Controller

bin/www, controllers/user.controller.js, models/index.js, models/user.js, package-lock.json, package.json, routes/users.js
- Create Register endpoint
- Create Register controller
COMO: usuario
QUIERO: registrarme en el sistema
PARA: ser parte del mismo
Criterios de aceptación: POST /auth/register Deberá validar los campos Nombre, Apellido, Email, Contraseña. La contraseña debe ser encriptada. Deberá devolver como respuesta el usuario generado
Validar
Encriptar contraseña
Almacenar en base de datos
Para validar utilizaremos express validator https://express-validator.github.io/docs/
_Postman screenshots_
- Succesfull request: 
- Existing email: 
- Missing data:
=> Ot155 32 - Endpoint registro de Usuarios

Middlewares/validateTestimonials.js, app.js, controllers/testimonials.controller.js, routes/testimonials.js
- Create Testimonials Route and Controller
- Create POST Method
=> Ot155 84 - Testimonial Post Endpoint

migrations/20220329171316-create-members.js, models/members.js
- Members model and migration created
[OT155-88](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT155/boards/229?modal=detail&selectedIssue=OT155-88)
=> OT155-88 Crear migración y modelo de Miembros

controllers/organizations.controller.js, migrations/20220329175241-create-entries.js, migrations/20220329193009-create-organizations.js, models/entries.js, models/organizations.js
This task was created to complete ticket OT155-17, I did not find a ticket in the backlog that asks to create the model and migration of Organizations
=> Ot155 40 - Crear migración y modelo de Novedades

migrations/20220329201053-create-activities.js, models/activities.js
Criterios de aceptación: Las Actividades de la ONG podrán ser gestionadas desde el backoffice. Nombre de tabla: activities. Contendrá los campos name, image, content, deletedAt (utilizada para soft delete)
=> Ot155 59 Crear migración y modelo de Actividades

app.js, controllers/categories.controller.js, routes/categories.js
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla, caso contrario devolver un error
=> Ot155 99 Endpoint Eliminación Categorías

app.js, controllers/auth.controller.js, routes/auth.js
/GET auth/me - Deberá devolver los datos del usuario autenticado, obteniendo al mismo desde el token enviado en el header Authorization
=> OT155-36 Endpoint datos usuario autenticado

controllers/testimonials.controller.js, routes/testimonials.js
-  Create Delete endpoint
-  Validate if testimonial ID exist
=> Ot155 86 - Endpoint Delete -Testimonials

auth/authRole.js, controllers/user.controller.js, models/user.js, routes/users.js
* created enpoint getUser
* change export by module.export in file authRole
* change moduleName 'user" by 'User'
=> Ot155-53 Endpoint para listar Usuarios

migrations/20220329175241-create-entries.js, models/entries.js
=> entries: models and migration update

controllers/activities.controllers.js, routes/activities.js
-Add Update-Activity Route and Controller
COMO usuario administrador
QUIERO actualizar una actividad existente
PARA mantener la información actualizada
Criterios de aceptación:
PUT /activities/:id - Deberá validar que la actividad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizarla y devolverla con los datos actualizados
_Postman screenshots_
- Successfull response
- 404 response
=> OT155-67 - Endpoint Actualización Actividades

app.js, controllers/member.controller.js, routes/members.js
- Member route created
- Member controller created
[OT155-89](https://alkemy-labs.atlassian.net/browse/OT155-89)
=> OT155-89 Endpoint para listar Miembros

migrations/20220405220927-create-contacts.js, models/contacts.js, package-lock.json
=> Ot155 71 - Crear migración y modelo de Contactos

controllers/user.controller.js, routes/users.js
PUT /users/:id - Deberá validar que el miembro existe y actualizarla, caso contrario devolver un error. También se deberá re-setear el token JWT en caso de que un usuario (administrador o no) actualizé su propio perfil.
=> Ot155 129 Endpoint Actualización usuarios

migrations/20220329193009-create-organizations.js, models/organizations.js
=> OT155-78 - Added social network urls to the organizations table

controllers/categories.controller.js, routes/categories.js
=> Ot155 97 - Endpoint Creation Categories

controllers/categories.controller.js, controllers/organizations.controller.js, migrations/20220329193009-create-organizations.js, routes/members.js, routes/organizations.js, seeders/20220421230415-create-organizations.js
=> Ot155 121 - Endpoint Organization Update

controllers/activities.controllers.js, routes/activities.js
- GET endpoint added
- GET by id endpoint added
- DELETE endpoint added
- JTW is needed for post, update and delete actions
=> Added activities missing endpoints

controllers/contacts.controller.js, routes/contacts.js
- GET endpoint added
- JWT is needed to get contacts
- Admin role is needed to get contacts
=> Missing endpoint added

controllers/contacts.controller.js
Cuando se registre un nuevo contacto en el sitio, enviar un email al usuario que completó el formulario agradeciendo su contacto. Para esto, utilizar el servicio de envío de emails.
=> OT155-75 Enviar email de contacto

app.js, controllers/slide.controller.js, migrations/20220320220159-create-slide.js, routes/slide.js, seeders/20220422145232-create-slides.js
=> Slide: seeder, route, controller added - these tasks were not in Jira

auth/authRole.js, migrations/20220405220927-create-contacts.js, models/contacts.js, seeders/20220422184207-create-contacts.js, seeders/20220422190126-create-members.js
- Contacts seeder created
- Members seeder created
- authRole fixed
- Contacts message type changed
=> Seeders db

controllers/categories.controller.js, routes/categories.js, routes/members.js
- Add Update Catefory controller
COMO usuario administrador
QUIERO modificar una categoría existente
PARA mantener la información actualizada
Criterios de aceptación:
PUT /categories/:id - Deberá validar que la categoría existe y actualizarla, caso contrario devolver un error
404:
Empry fields:
Successfull request:
=> OT155-98 - Endpoint Actualización Categorías
